version: '3.4'
services:
  filebeat:
    build:
      context: ./filebeat
    ports:
      - 9100:80
    volumes:
      - ./logs/apache.log:/usr/share/filebeat/apache.log

  logstash:
    build:
      context: ./logstash
    depends_on:
      - filebeat
    ports:
      - 9600:9600

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    build:
      context: ./kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
